### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Jacques2101** [suhasghorp/PortAnalyticsAdvanced#1]
Interesting but I have one question: what are the difference btw EDHEC_risk_kit_XXX (xxx from 201 to 206) ? 
thx.

**Comment by suhasghorp** [comment]
As part of the course, we work on these files progressively. We start with 201 and slowly build towards 206 as the course progresses. Hopefully that answers your question.

**Comment by Jacques2101** [comment]
So does it mean that The EDHEC_risk_kit_201 file include a subset of the functions in EDHEC_risk_kit_206 ? 
with of these file EDHEC_risk_kit_XXX include all ? 
Thx.
